import React from "react"

import organExperienceImage from "../../images/organ_experience.png"
import positivelyBaroqueImage from "../../images/positively_baroque.jpg"

const OtherStations = () => {
	return (
		<div className="home-section home-other-stations">
			<div id="other-stations">
				<div className="other-station-section">
					<a
						href="http://www.positivelybaroque.com/"
						target="_blank"
						rel="noreferrer">
						<img
							src={positivelyBaroqueImage}
							className="other-station-logo"
							alt="Positively Baroque Logo"
						/>
					</a>
					<div className="other-station-title-text-container">
						<h2 className="other-station-section-title">Positively Baroque</h2>
						<p className="other-station-section-text">
							Positively Baroque features just the music from our library of the
							Baroque and earlier periods. Like Organlive, the station
							broadcasts 24 hours a day and you can tune in with just a single
							click.
						</p>
					</div>
				</div>
				<div className="other-station-section">
					<a
						href="http://www.organexperience.com/"
						target="_blank"
						rel="noreferrer">
						<img
							src={organExperienceImage}
							className="other-station-logo"
							alt="The Organ Experience Logo"
						/>
					</a>
					<div className="other-station-title-text-container">
						<h2 className="other-station-section-title">
							The Organ Experience
						</h2>
						<p className="other-station-section-text">
							The Organ Experience is our newest addition to our lineup. There
							you can hear blocks of 30 minutes to 2 hours of similarly-themed
							music, such as music from a single period, country, or organs by a
							single builder. The station is automated and the playlists are
							generated by a computer, so you never know what you'll hear.
						</p>
					</div>
				</div>
			</div>
		</div>
	)
}

export default OtherStations
