import React from "react"

const Socials = () => {
	return (
		<div className="home-section home-social-stations">
			<div id="social-other-divider"></div>
			<div id="other-stations">
				<div className="other-station-section">
					<h2 className="other-station-section-title">Positively Baroque</h2>
					<p className="other-station-section-text">
						Positively Baroque features just the music from our library of the
						Baroque and earlier periods. Like Organlive, the station broadcasts
						24 hours a day and you can tune in with just a single click.
					</p>
				</div>
				<div className="other-station-section">
					<h2 className="other-station-section-title">The Organ Experience</h2>
					<p className="other-station-section-text">
						The Organ Experience is our newest addition to our lineup. There you
						can hear blocks of 30 minutes to 2 hours of similarly-themed music,
						such as music from a single period, country, or organs by a single
						builder. The station is automated and the playlists are generated by
						a computer, so you never know what you'll hear.
					</p>
				</div>
			</div>
		</div>
	)
}

export default Socials
